name: Build Package

on:
  workflow_dispatch:

  # push:
    #branches: [ "master", "main", "*" ]
    # branches: [ "*" ]
    
  repository_dispatch:
    types:
      - linux-xanmod*/*

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/base
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        shell: bash
        run: |
          sudo pacman -Sy --noconfirm --needed \
          git \
          openssh \
          xz \
          tmate
          
          #add biglinux repository
          sudo sed -i '/\[core\]/{h;s/.*/\[biglinux-update-stable\]/;p;x;}' /etc/pacman.conf
          sudo sed -i '/\[core\]/{h;s/.*/SigLevel = PackageRequired/;p;x;}' /etc/pacman.conf
          sudo sed -i '/\[core\]/{h;s/.*/Server = https:\/\/repo.biglinux.com.br\/update-stable\/$arch/;p;x;}' /etc/pacman.conf
          sudo sed -i '/\[core\]/{h;s/.*//;p;x;}' /etc/pacman.conf
          echo '
          [biglinux-testing]
          SigLevel = PackageRequired
          Server = https://repo.biglinux.com.br/testing/$arch' | sudo tee -a /etc/pacman.conf
          echo '
          [biglinux-stable]
          SigLevel = PackageRequired
          Server = https://repo.biglinux.com.br/stable/$arch' | sudo tee -a /etc/pacman.conf
          
          sudo git clone --depth 1 https://github.com/biglinux/biglinux-keyring.git
          pushd biglinux-keyring
            sudo install -m0644 biglinux.gpg /usr/share/pacman/keyrings/
            sudo install -m0644 biglinux-trusted /usr/share/pacman/keyrings/
            sudo install -m0644 biglinux-trusted /usr/share/pacman/keyrings/
          popd
          sudo rm -rf biglinux-keyring
          
          sudo git clone https://github.com/biglinux/biglinux-key.git
          sudo mkdir -p /etc/pacman.d/gnupg/
          sudo cp -r biglinux-key/usr/share/pacman/keyrings/* /etc/pacman.d/gnupg/
          sudo rm -r biglinux-key

      # Tmate ##
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          install-dependencies: false

      # - name: Update github
      #   run: |
      #     git add --all
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     if [ -n "$(git commit -m "new translate" -a | grep "nothing to commit")" ];then exit 0; fi

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}

      # - name: Send Hooks BigLinux Build Package
      #   shell: bash
      #   run: |
      #     curl -X POST -H "Accept: application/json" -H "Authorization: token ${{ secrets.WEBHOOK_TOKEN }}" --data '{"event_type": "${{ github.repository }}", "client_payload": { "branch": "${{ github.ref_name }}", "url": "https://github.com/${{ github.repository }}", "version": "1.2.3"}}' https://api.github.com/repos/BigLinux-Package-Build/build-package/dispatches
