name: Build Package

on:
  workflow_dispatch:

  # push:
    #branches: [ "master", "main", "*" ]
    # branches: [ "*" ]
    
  repository_dispatch:
    types:
      - linux-xanmod*/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install \
          git 

      # Tmate ##
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      # - name: Update github
      #   run: |
      #     git add --all
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     if [ -n "$(git commit -m "new translate" -a | grep "nothing to commit")" ];then exit 0; fi

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}

      # - name: Send Hooks BigLinux Build Package
      #   shell: bash
      #   run: |
      #     curl -X POST -H "Accept: application/json" -H "Authorization: token ${{ secrets.WEBHOOK_TOKEN }}" --data '{"event_type": "${{ github.repository }}", "client_payload": { "branch": "${{ github.ref_name }}", "url": "https://github.com/${{ github.repository }}", "version": "1.2.3"}}' https://api.github.com/repos/BigLinux-Package-Build/build-package/dispatches
